-- Table: public.clienti

-- DROP TABLE IF EXISTS public.clienti;

CREATE TABLE IF NOT EXISTS public.clienti
(
    id_cliente integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nome character varying(20) COLLATE pg_catalog."default" NOT NULL,
    codice_fiscale character varying(20) COLLATE pg_catalog."default" NOT NULL,
    email character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT cliente_pkey PRIMARY KEY (id_cliente),
    CONSTRAINT codice_fiscale UNIQUE (codice_fiscale)
        INCLUDE(codice_fiscale)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.clienti
    OWNER to postgres;
    
-- Table: public.linee

-- DROP TABLE IF EXISTS public.linee;

CREATE TABLE IF NOT EXISTS public.linee
(
    id_linea integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    numero character varying(20) COLLATE pg_catalog."default" NOT NULL,
    tipo character varying(10) COLLATE pg_catalog."default" NOT NULL,
    stato character varying(10) COLLATE pg_catalog."default" NOT NULL,
    id_cliente integer NOT NULL,
    CONSTRAINT linea_pkey PRIMARY KEY (id_linea),
    CONSTRAINT numero UNIQUE (numero)
        INCLUDE(numero),
    CONSTRAINT id_cliente FOREIGN KEY (id_cliente)
        REFERENCES public.clienti (id_cliente) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.linee
    OWNER to postgres;
    
-- Table: public.chiamate

-- DROP TABLE IF EXISTS public.chiamate;

CREATE TABLE IF NOT EXISTS public.chiamate
(
    id_chiamata bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    data_inizio timestamp without time zone NOT NULL,
    data_fine timestamp without time zone NOT NULL,
    durata bigint NOT NULL,
    id_linea integer NOT NULL,
    CONSTRAINT chiamate_pkey PRIMARY KEY (id_chiamata),
    CONSTRAINT id_linea FOREIGN KEY (id_linea)
        REFERENCES public.linee (id_linea) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.chiamate
    OWNER to postgres;


